# Generated by Django 3.0.8 on 2020-08-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_remove_company_user_com'),
        ('api_usersite', '0003_remove_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_user.Company'),
        ),
    ]
