# Generated by Django 3.0.8 on 2020-08-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usersite', '0004_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settinguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.BooleanField(default=True)),
                ('set_kanzyo', models.BooleanField(default=True)),
                ('set_name', models.BooleanField(default=True)),
                ('set_code', models.BooleanField(default=True)),
                ('set_which', models.BooleanField(default=True)),
                ('set_number', models.BooleanField(default=True)),
                ('set_price', models.BooleanField(default=True)),
                ('set_remark', models.BooleanField(default=True)),
                ('set_pic', models.BooleanField(default=True)),
            ],
        ),
    ]
