# Generated by Django 3.0.8 on 2020-08-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_remove_company_user_com'),
        ('api_usersite', '0008_settinguser_set_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.Company'),
        ),
    ]
