# Generated by Django 3.0.6 on 2020-07-12 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaiko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanzyo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('1', '新品'), ('2', '中古')], default=1, max_length=40)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=50)),
                ('total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('remark', models.CharField(max_length=70)),
                ('pic', models.ImageField(upload_to=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
