# Generated by Django 3.0.8 on 2020-07-17 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zaikodata', '0002_auto_20200716_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('res', models.CharField(max_length=50)),
                ('create_com', models.DateTimeField(auto_now_add=True)),
                ('updated_com', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
