# Generated by Django 3.0.8 on 2020-07-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_zaikodata', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
