# Generated by Django 3.0.8 on 2020-08-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zaikodata', '0005_zaiko_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaiko',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
