# Generated by Django 3.0.8 on 2020-08-20 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zaikodata', '0006_auto_20200809_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaiko',
            name='code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='kanzyo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='remark',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '新品'), ('2', '中古')], default=1, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='zaiko',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
