# Generated by Django 3.0.8 on 2020-07-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
