# Generated by Django 3.0.6 on 2020-07-10 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZaikoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_kanzyo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model_which', models.CharField(choices=[('1', '新品'), ('2', '中古')], default=1, max_length=40)),
                ('model_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model_name', models.CharField(max_length=50)),
                ('model_total_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model_remark', models.CharField(max_length=70)),
                ('model_pic', models.ImageField(upload_to=None)),
                ('model_create_at', models.DateTimeField(auto_now_add=True)),
                ('model_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
